# Autogenerated wrapper script for ProtocolBuffersSDK_static_jll for armv7l-linux-musleabihf-cxx11
export binary_symbol, libprotobuf, libprotobuf_lite, libprotobuf_lite_pkgconfig, libprotobuf_pkgconfig, libprotoc

using CompilerSupportLibraries_jll
using Zlib_jll
JLLWrappers.@generate_wrapper_header("ProtocolBuffersSDK_static")
JLLWrappers.@declare_executable_product(binary_symbol)
JLLWrappers.@declare_file_product(libprotobuf)
JLLWrappers.@declare_file_product(libprotobuf_lite)
JLLWrappers.@declare_file_product(libprotobuf_lite_pkgconfig)
JLLWrappers.@declare_file_product(libprotobuf_pkgconfig)
JLLWrappers.@declare_file_product(libprotoc)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, Zlib_jll)
    JLLWrappers.@init_executable_product(
        binary_symbol,
        "bin/protoc",
    )

    JLLWrappers.@init_file_product(
        libprotobuf,
        "lib/libprotobuf.a",
    )

    JLLWrappers.@init_file_product(
        libprotobuf_lite,
        "lib/libprotobuf-lite.a",
    )

    JLLWrappers.@init_file_product(
        libprotobuf_lite_pkgconfig,
        "lib/pkgconfig/protobuf-lite.pc",
    )

    JLLWrappers.@init_file_product(
        libprotobuf_pkgconfig,
        "lib/pkgconfig/protobuf.pc",
    )

    JLLWrappers.@init_file_product(
        libprotoc,
        "lib/libprotoc.a",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
