# Autogenerated wrapper script for ProtocolBuffersSDK_static_jll for x86_64-apple-darwin
export libprotobuf, libprotobuf_lite, libprotobuf_lite_pkgconfig, libprotobuf_pkgconfig, libprotoc, protoc

using CompilerSupportLibraries_jll
using Zlib_jll
JLLWrappers.@generate_wrapper_header("ProtocolBuffersSDK_static")
JLLWrappers.@declare_file_product(libprotobuf)
JLLWrappers.@declare_file_product(libprotobuf_lite)
JLLWrappers.@declare_file_product(libprotobuf_lite_pkgconfig)
JLLWrappers.@declare_file_product(libprotobuf_pkgconfig)
JLLWrappers.@declare_file_product(libprotoc)
JLLWrappers.@declare_executable_product(protoc)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, Zlib_jll)
    JLLWrappers.@init_file_product(
        libprotobuf,
        "lib/libprotobuf.a",
    )

    JLLWrappers.@init_file_product(
        libprotobuf_lite,
        "lib/libprotobuf-lite.a",
    )

    JLLWrappers.@init_file_product(
        libprotobuf_lite_pkgconfig,
        "lib/pkgconfig/protobuf-lite.pc",
    )

    JLLWrappers.@init_file_product(
        libprotobuf_pkgconfig,
        "lib/pkgconfig/protobuf.pc",
    )

    JLLWrappers.@init_file_product(
        libprotoc,
        "lib/libprotoc.a",
    )

    JLLWrappers.@init_executable_product(
        protoc,
        "bin/protoc",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
